repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.11
        # Black doesn't use file filters for inclusion, it formats all Python files by default.

  - repo: https://github.com/PyCQA/flake8

