games = ['Counter-Strike 2',
 'Palworld',
 'Dota 2',
 'Source SDK Base 2007',
 'HELLDIVERS™ 2',
 'Apex Legends',
 "Baldur's Gate 3",
 'Grand Theft Auto V',
 'Call of Duty®',
 'PUBG: BATTLEGROUNDS',
 "Tom Clancy's Rainbow Six Siege",
 'Rust',
 'Warframe',
 'War Thunder',
 'Team Fortress 2',
 'Wallpaper Engine',
 'Football Manager 2024',
 'Granblue Fantasy: Relink',
 'Enshrouded',
 'Unturned',
 'Lost Ark',
 'Lethal Company',
 'EA SPORTS FC™ 24',
 'ELDEN RING',
 'MIR4',
 'NARAKA: BLADEPOINT',
 'DayZ',
 "Sid Meier's Civilization VI",
 'Red Dead Redemption 2',
 'Overwatch® 2',
 'Destiny 2',
 'Governor of Poker 3',
 'Stardew Valley',
 'Terraria',
 'The Sims™ 4',
 'Cyberpunk 2077',
 'Geometry Dash',
 'Hearts of Iron IV',
 'FINAL FANTASY XIV Online',
 'Rocket League',
 'Yu-Gi-Oh! Master Duel',
 'Project Zomboid',
 'VRChat',
 'The Elder Scrolls V: Skyrim Special Edition',
 'Monster Hunter: World',
 'Spacewar',
 'Dead by Daylight',
 'Black Desert',
 'Persona 3 Reload',
 'PAYDAY 2',
 'THE FINALS',
 'TEKKEN 8',
 'Palworld Dedicated Server',
 "Hero's Land",
 'Euro Truck Simulator 2',
 '7 Days to Die',
 'ARK: Survival Evolved',
 'Left 4 Dead 2',
 'RimWorld',
 'Path of Exile',
 "Garry's Mod",
 'The Binding of Isaac: Rebirth',
 'Valheim',
 'Brawlhalla',
 'Farming Simulator 22',
 'ARK: Survival Ascended',
 'SMITE',
 'Fallout 4',
 "Sid Meier's Civilization V",
 'Crosshair X',
 'Last Epoch',
 'Total War: WARHAMMER III',
 'Age of Empires II: Definitive Edition',
 'Crusader Kings III',
 'Soundpad',
 'Mount & Blade II: Bannerlord',
 'Europa Universalis IV',
 'Cookie Clicker',
 'Bloons TD 6',
 'The Elder Scrolls Online',
 'BeamNG.drive',
 'Dead Island Riptide Definitive Edition',
 'New World',
 'Factorio',
 'Like a Dragon: Infinite Wealth',
 "Don't Starve Together",
 'tModLoader',
 'Football Manager 2023',
 'Phasmophobia',
 'Hogwarts Legacy',
 'Stellaris',
 'The Witcher 3: Wild Hunt',
 'Battlefield™ V',
 'Arma 3',
 'Summoners War',
 'Assetto Corsa',
 'SCUM',
 'Fallout 76',
 'Persona 5 Royal',
 'Microsoft Flight Simulator',
 'Squad',
 'Hunt: Showdown',
 'Slay the Spire',
 'Sea of Thieves',
 'American Truck Simulator',
 'Albion Online',
 'Risk of Rain 2',
 'Battlefield™ 2042',
 'Satisfactory',
 'Forza Horizon 5',
 'eFootball™ 2024',
 'Conan Exiles',
 'OBS Studio',
 'Deep Rock Galactic',
 'Counter-Strike',
 'Madden NFL 24',
 'VPet',
 'Diablo® IV',
 'VTube Studio',
 'Age of Empires IV: Anniversary Edition',
 'Hell Let Loose',
 'Cities: Skylines',
 'Legends of Idleon MMO',
 'DARK SOULS™ III',
 'Paladins',
 'Blender',
 'Starfield',
 'Halo: The Master Chief Collection',
 'Ready or Not',
 'NBA 2K24',
 'Street Fighter™ 6',
 'Magic: The Gathering Arena',
 'People Playground',
 'MARVEL SNAP',
 'Halo Infinite',
 'Stumble Guys',
 'MapleStory',
 'EA SPORTS™ FIFA 23',
 'Russian Fishing 4',
 'Undisputed',
 'Melvor Idle',
 'World of Warships',
 'Oxygen Not Included',
 'Crab Game',
 'Victoria 3',
 'Hades',
 'Dyson Sphere Program',
 'YoloMouse',
 'Call of Duty: Black Ops III',
 'Limbus Company',
 'Battlefield 1 ™',
 'NBA 2K23',
 'World of Tanks Blitz',
 'MONSTER HUNTER RISE',
 'Hollow Knight',
 'Subnautica',
 'Fallout: New Vegas',
 'Farlight 84',
 'Kenshi',
 'Aimlabs',
 'Cities: Skylines II',
 'Sons Of The Forest',
 'Total War: ROME II - Emperor Edition',
 'DARK SOULS™: REMASTERED',
 'It Takes Two',
 'STAR WARS™: The Old Republic™',
 'Poppy Playtime',
 'Resident Evil 4',
 'Among Us',
 'Divinity: Original Sin 2',
 'Unnamed Space Idle',
 'NGU IDLE',
 'Space Engineers',
 '雀魂麻将(MahjongSoul)',
 'Vampire Survivors',
 'Warhammer 40,000: Darktide',
 'Idle Champions of the Forgotten Realms',
 'Crossout',
 'Shop Titans',
 'Yu-Gi-Oh! Duel Links',
 "No Man's Sky",
 'Football Manager 2022',
 'Grand Theft Auto IV: The Complete Edition',
 'GrandChase',
 'Aseprite',
 'Raft',
 'Tabletop Simulator',
 'Batman™: Arkham Knight',
 'Age of Empires III: Definitive Edition',
 'For Honor',
 'Total War: THREE KINGDOMS',
 'XCOM 2',
 'Total War: MEDIEVAL II - Definitive Edition',
 'Crosshair V2',
 'Guild Wars 2',
 'FIFA 22',
 'Cult of the Lamb',
 'The Isle',
 'Sekiro™: Shadows Die Twice',
 'ヘブンバーンズレッド',
 'SCP: Secret Laboratory',
 'Crush Crush',
 'Timberborn',
 '小黑盒加速器',
 'God of War',
 'ARMORED CORE™ VI FIRES OF RUBICON™',
 'Party Animals',
 'BattleBit Remastered',
 'SnowRunner',
 'Cell to Singularity - Evolution Never Ends',
 'Elite Dangerous',
 'Summoners War: Chronicles',
 'RuneScape',
 'Age of Empires II (2013)',
 'theHunter: Call of the Wild™',
 'Brotato',
 'Against the Storm',
 'Yakuza: Like a Dragon',
 'Days Gone',
 'Mass Effect™ Legendary Edition',
 'ULTRAKILL',
 'The Forest',
 'RISK: Global Domination',
 'Dying Light',
 'Tap Ninja',
 'Counter-Strike: Source',
 'Dying Light 2',
 'MX Bikes',
 'Farmer Against Potatoes Idle',
 'Warhammer 40,000: Rogue Trader',
 'Goose Goose Duck',
 'Plants vs. Zombies: Game of the Year',
 'Clicker Heroes',
 'EVE Online',
 'Horizon Zero Dawn™ Complete Edition',
 'Red Dead Online',
 'Wallpaper Alive',
 'FINAL FANTASY VII REMAKE INTERGRADE',
 'DAVE THE DIVER',
 'Total War: EMPIRE - Definitive Edition',
 'Medieval Dynasty',
 'Broken Arrow Playtest',
 'DEAD OR ALIVE Xtreme Venus Vacation',
 'Planet Zoo',
 'F1® 23',
 'World of Tanks',
 'Lost Light',
 'Borderlands 3',
 'Yakuza 0',
 'Mount & Blade: Warband',
 'Total War: SHOGUN 2',
 'V Rising',
 'Teardown',
 '鬼谷八荒 Tale of Immortal',
 'ShareX',
 'Company of Heroes 2',
 'Total War: WARHAMMER II',
 'Anno 1800',
 'Fishing Planet',
 'Forza Horizon 4',
 'Coral Island',
 'STAR WARS Jedi: Survivor™',
 'Grim Dawn',
 'Backpack Battles Demo',
 'Crusader Kings II',
 'Borderlands 2',
 "DEATH STRANDING DIRECTOR'S CUT",
 'OVR Advanced Settings',
 "Tom Clancy's The Division 2",
 'Rec Room',
 'Farming Simulator 19',
 'Kingdom Come: Deliverance',
 'HITMAN 3',
 "Assassin's Creed Odyssey",
 'Pathfinder: Wrath of the Righteous - Enhanced Edition',
 'CarX Drift Racing Online',
 'Darkest Dungeon®',
 "Dragon's Dogma: Dark Arisen",
 'Age of Mythology: Extended Edition',
 'STAR WARS™ Empire at War: Gold Pack',
 'DARK SOULS™ II: Scholar of the First Sin',
 'Phantasy Star Online 2 New Genesis',
 'METAL GEAR SOLID V: THE PHANTOM PAIN',
 'Suicide Squad: Kill the Justice League',
 'Combat Master',
 'ASTLIBRA ～生きた証～ Revision',
 'Marvel’s Spider-Man Remastered',
 'Transport Fever 2',
 'Stormworks: Build and Rescue',
 'Persona 4 Golden',
 'STALCRAFT',
 'The Elder Scrolls V: Skyrim',
 'Escape the Backrooms',
 'Overcooked! 2',
 'My Time at Sandrock',
 'Assetto Corsa Competizione',
 'Deep Rock Galactic: Survivor',
 'Need for Speed™ Heat',
 'Tomb Raider I-III Remastered Starring Lara Croft',
 'Battlefield 4™']