name: Issue Automation

on:
  issues:
    types: [opened, edited]
jobs:
  convert-tasklist-to-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Convert Tasklist to Issue
        uses: actions/github-script@v5
        with:
          script: |
            const issue_number = context.issue.number;
            const github_token = process.env.GITHUB_TOKEN;
            const octokit = github.getOctokit(github_token);

            const issue = await octokit.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });

            const body = issue.data.body;
            const milestone = issue.data.milestone;

            // Tasklist 항목을 찾아 새 이슈로 변환하는 로직 작성
            // 예: - [ ] Task 1 -> 새 이슈 생성
